modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GPLv3"
issueTrackerURL = "https://github.com/TeamMoegMC/ImmersiveIndustry/issues"
[[mods]] #mandatory
modId = "immersiveindustry" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Immersive Industry" #mandatory
authors = "[TeamMoeg] dashuaibia khjxiaogu YueSha"
itemIcon="immersiveindustry:electrolyzer"
displayURL="https://www.curseforge.com/minecraft/mc-mods/immersive-industry"
description = '''
Introduce more various process and energy production machines to Immersive Engineering.

Discord: https://discord.gg/BWn6E94
'''
[[dependencies.immersiveindustry]]
    modId = "forge"
    mandatory = true
    versionRange = "[36,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.immersiveindustry]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.immersiveindustry]]
    modId="immersiveengineering"
    mandatory=true
    versionRange="[1.20.1-10.1.0,)"
    ordering="BEFORE"
    side="BOTH"

